blank_issues_enabled: true
contact_links:
  - name: Issue with WebView2
    url:  https://github.com/MicrosoftEdge/WebViewFeedback/issues/new/choose
    about: Please open bugs and feature requests for the WebView2 control in the Feedback repo
